global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v2

scrape_configs:
  - job_name: 'pve-exporter'
    static_configs:
      - targets:
          - monitoring.home:9221  # Proxmox VE node with PVE exporter.
    metrics_path: /pve
    params:
      target: ['10.0.10.114']

  - job_name: 'adguard'
    static_configs:
      - targets: ['monitoring.home:9618']

  - job_name: 'tailscale_subnet_router'
    static_configs:
      - targets:
          - 100.68.37.129:5252
    metrics_path: /metrics

  - job_name: 'kube-exporters'
    scrape_interval: 10s
    static_configs:
      - targets: ['controlp-pi-home-01.tail15aad.ts.net:9100']
        labels:
          service: 'controlp-pi-home-01'
      - targets: ['worker-pi-home-01.tail15aad.ts.net:9100']
        labels:
          service: 'worker-pi-home-01'
      - targets: [ 'debian-1.tail15aad.ts.net:9100' ]
        labels:
          service: 'debian-1'