# A full system base playbook to initialise a key-only ssh, install packages and the hardening of the SSH.
# Note that installing this WILL break any pre-existing installs and CAN render your remote host inaccessible.
# This is because it skips generating
---
- name: Initial SSH Setup
  hosts: all
  gather_facts: no
  vars:
    # Ensures that the local ssh keygen process is done locally, first.
    ansible_connection: local
  roles:
    - role: base-setup
      vars:
        setup_local_ssh: true
        setup_packages: false
        setup_ssh_config: false

# A second play, where all operations are done against the remote hosts.
- name: System Configuration
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: base-setup
      vars:
        setup_local_ssh: false
        setup_packages: true
        setup_ssh_config: true