kube_hosts:
  hosts:
    debian:
      ansible_user: syahshiimi
      ansible_host: 10.0.10.166
      ansible_connection: ssh
      ansible_ssh_private_key_file: ~/.ssh/debian

#    controlp_pi_home_01:
#      ansible_user: "{{ username }}"
#      ansible_host: 10.0.10.45
#      ansible_connection: ssh
#      ansible_ssh_private_key_file: ~/.ssh/controlp-pi-home-01
#    worker_pi_home_01:
#      ansible_user: "{{ username }}"
#      ansible_host: 10.0.10.33
#      ansible_connection: ssh
#      ansible_ssh_private_key_file: ~/.ssh/worker-pi-home-01